madesroches/micromegas

- python/micromegas/micromegas/client.py
- python/micromegas/tests/test_log.py
- rust/analytics-srv/src/main.rs
- rust/analytics/src/analytics_service.rs
- rust/analytics/src/lakehouse/query.rs
- rust/analytics/src/lakehouse/view_factory.rs
- rust/public/src/servers/analytics.rs
- rust/telemetry-admin-cli/src/telemetry_admin.rs
log_entries and measures are implicitly available to sql queries using client.query
> query_request

- rust/analytics/src/lakehouse/batch_update.rs
- rust/analytics/src/lakehouse/block_partition_spec.rs
- rust/analytics/src/lakehouse/blocks_view.rs
- rust/analytics/src/lakehouse/merge.rs
- rust/analytics/src/lakehouse/metadata_partition_spec.rs
- rust/analytics/src/lakehouse/partition_cache.rs
- rust/analytics/src/lakehouse/partition_source_data.rs
- rust/analytics/src/lakehouse/query.rs
- rust/analytics/src/lakehouse/sql_partition_spec.rs
- rust/analytics/src/lakehouse/view.rs
- rust/analytics/src/lakehouse/write_partition.rs
- rust/analytics/tests/sql_view_test.rs
- rust/public/src/servers/maintenance.rs
Run a SQL query on a known set of parquet files without going through the more flexible query_view API
> query_partitions

- rust/telemetry-sink/src/request_decorator.rs
This PR does several little things around the `RequestDecorator` trait.
1. It changes the `Result` type to **not** depend on `anyhow`.
2. It adds the ability for `RequestDecorator` implementers to express whether a request decoration error can be retried or not by the underlying MicroMegas logic. (The previous behavior was to **always** retry).
3. It auto-implements `RequestDecorator` on all `Arc<T: RequestDecorator + Sync>` which allows some non-clonable types to directly implement `RequestDecorator` without having to wrap them.
> Exposed retry logic to request decorator implementors

- rust/telemetry-sink/src/tracing_interop.rs
This PR adds some documentation and exposes publicly the `TracingCaptureLayer`.
> Added missing  for the TracingLayer

- rust/Cargo.lock
- rust/Cargo.toml
This changes dependencies on reqwest to not depend on openssl, which causes cross-compilation issues down the line.
> Removed dependency on openssl

- rust/analytics/src/lakehouse/jit_partitions.rs
- rust/analytics/src/lakehouse/log_view.rs
- rust/analytics/src/lakehouse/metrics_view.rs
- rust/analytics/src/lakehouse/thread_spans_view.rs
when requesting a small portion of the log entries of a long-running process we should not need to consider all the blocks
> divide jit partitions into segments

- rust/tracing/src/macros.rs
This PR changes `imetric` and `fmetric` macros to accept expressions instead of literal, which allows accepting constants.
> Fixed macros needlessly required literals

- doc/cost/MICROMEGAS_VS_DATADOG.md
- doc/cost/MICROMEGAS_VS_DYNATRACE.md
- doc/cost/MICROMEGAS_VS_ELASTIC.md
- doc/cost/MICROMEGAS_VS_GRAFANA.md
- doc/cost/MICROMEGAS_VS_NEWRELIC.md
- doc/cost/MICROMEGAS_VS_SPLUNK.md
The cost comparison documents were confusing the total number of events over the 90-day retention period with the monthly ingestion rate. This commit clarifies the workload definition by separating the total events from the monthly ingestion rate and updates the cost calculations accordingly.
Author: Gemini <gemini@google.com>
> docs: Correct workload definition in cost comparison docs

- .github/workflows/publish-rust-docs.yml
This commit adds the necessary `pages: write` and `id-token: write` permissions to the `publish-rust-docs.yml` workflow. This resolves the "Permission denied" error encountered when the GitHub Actions bot attempts to deploy documentation to GitHub Pages.
> feat: Add GitHub Pages permissions to publish-rust-docs workflow

- doc/presentation-template/package-lock.json
- doc/presentation-template/package.json
- Fixes Dependabot security alert #21 (CVE-2025-54798)
- Updates vulnerable `tmp` package from 0.0.33 to secure version 0.2.4
- Resolves arbitrary temporary file write vulnerability via symbolic link exploitation
- Added npm override for `tmp: "0.2.4"` in presentation template package.json
- Updated package-lock.json to enforce secure version across dependency tree
- Vulnerability was in transitive dependency: external-editor → tmp
- **CVE**: CVE-2025-54798
- **Severity**: Low (CVSS 2.5)
- **Issue**: Arbitrary temporary file/directory write via symbolic link `dir` parameter
- **Fix**: Version 0.2.4 properly handles symbolic links in path resolution
Closes #21
> Fix Dependabot alert #21: Update tmp package to resolve CVE-2025-54798

- CHANGELOG.md
- README.md
- Update README to reflect current project focus on async span tracing
- Move July 2025 status from README to CHANGELOG.md for better organization
- Highlight August 2025 async tracing developments
- **README.md**: Shift focus from query federation to async span tracing, featuring:
- `micromegas_main` proc macro as drop-in replacement for `tokio::main`
- Enhanced `#[span_fn]` macro supporting both sync and async functions
- `InstrumentedFuture` wrapper for manual async instrumentation
- Thread-safe tokio runtime integration
- **CHANGELOG.md**: Add July 2025 entry with version 0.11.0 and HTTP gateway work
> Update README to focus on async span tracing

- README.md
Fix markdown formatting in the "Current Status & Roadmap" section for better visual hierarchy.
- Change "August 2025" from bullet point to proper header (`###`)
- Convert nested bullet points to use single asterisks for consistent formatting
- Improve readability by creating clear hierarchical structure:
- Level 2: "Current Status & Roadmap"
- Level 3: "August 2025" 
- Bullet points: Individual async tracing features
> Fix README markdown formatting for better hierarchy

- AI_GUIDELINES.md
- CLAUDE.md
- rust/analytics/tests/async_span_tests.rs
- rust/tracing/proc-macros/src/lib.rs
- rust/tracing/src/dispatch.rs
- rust/tracing/src/guards.rs
- rust/tracing/src/spans/events.rs
- rust/tracing/src/spans/instrumented_future.rs
- Enhanced async span tracing infrastructure with call stack tracking
- Unified span instrumentation macros - `#[span_fn]` now handles both sync and async functions
- Removed deprecated `#[instrument_async]` macro in favor of unified approach
- Added comprehensive development guidelines documentation
- **Async call stack tracking**: Improved async span instrumentation using `InstrumentedFuture`
- **Unified macro approach**: `#[span_fn]` now automatically detects sync vs async functions
- **Deprecated macro removal**: Eliminated `#[instrument_async]` and migrated all usages
- **Documentation**: Added CLAUDE.md and expanded AI_GUIDELINES.md with architecture overview and commands
All async span tests passing (3/3), verifying compatibility and functionality.
> Async span tracing improvements and macro unification

- AI_GUIDELINES.md
- local_test_env/dev-stop.py
- local_test_env/dev.py
- rust/telemetry-ingestion-srv/test/generator.rs
- rust/tracing/proc-macros/src/lib.rs
- rust/tracing/tests/test_macros.rs
- Add Python scripts for local development workflow (`dev.py` and `dev-stop.py`)  
- Enhance telemetry generator with sync/async span examples and proper metrics
- Fix proc macro imports to use prelude patterns
- Add development guidelines for commit messages and PR creation
> Local dev scripts and async tracing enhancements

- .gitignore
- AI_GUIDELINES.md
- build/rust_coverage.py
- local_test_env/dev.py
- Add Rust coverage script with tarpaulin integration and HTML report generation
- Add Python black formatting requirements to development workflow
- Fix dev.py relative path issues for robust script execution from any directory
- Add sequential service startup with health checks for proper dependency management
> Add Rust coverage script and improve dev.py

- mkdocs/docs/cost-comparisons/datadog.md
- mkdocs/docs/cost-comparisons/elastic.md
- mkdocs/docs/cost-comparisons/splunk.md
- mkdocs/docs/query-guide/python-api.md
- mkdocs/docs/query-guide/quick-start.md
- mkdocs/docs/query-guide/schema-reference.md
- mkdocs/mkdocs.yml
- Fixed Python `connect()` function documentation to accurately reflect it takes no arguments
- Resolved all MkDocs build warnings for cleaner documentation builds
- Corrected connection endpoint from port 8080 to 32010 (FlightSQL service port)
- **Python API documentation**: Corrected `connect()` function description - it doesn't accept arguments and connects to `grpc://localhost:50051`
- **Navigation fixes**: Removed broken links to non-existent architecture pages (`components.md`, `data-flow.md`)
- **Reference citations**: Reformatted citation links to avoid mkdocs_autorefs warnings
- **Anchor links**: Fixed internal anchor links in schema-reference.md to match actual section IDs
- **Connection examples**: Added example showing how to use `FlightSQLClient` directly for custom endpoints
> Fix documentation build warnings and Python API accuracy

- rust/Cargo.lock
- rust/Cargo.toml
- Updates tracing-subscriber from 0.3.18 to 0.3.20 to address security vulnerability
- Fixes CVE-2025-58160 / GHSA-xwfj-jgwm-7wp5 (ANSI escape sequence injection)
- Prevents untrusted user input from manipulating terminal output through ANSI escape sequences
Fixes #23 (Dependabot security alert)
> Fix CVE-2025-58160: Update tracing-subscriber to 0.3.20

- ai_tasks/completed/jit_refactor.md
- ai_tasks/jit_refactor.md
- rust/analytics/src/lakehouse/log_view.rs
- rust/analytics/src/lakehouse/metrics_view.rs
- Replace stream-level iteration with process-level partition generation in metrics and log views
- Use `generate_process_jit_partitions` instead of `generate_stream_jit_partitions` 
- Remove manual stream iteration loops and simplify error handling
- **metrics_view.rs**: Use `generate_process_jit_partitions` with "metrics" tag
- **log_view.rs**: Use `generate_process_jit_partitions` with "log" tag
- Remove unused `list_process_streams_tagged` imports
- Eliminate manual stream iteration loops in both views
- Simplify error handling from stream-specific to process-level
- Reduced database queries from per-stream to per-process
- Better parallelization with process-level batching
- Simplified code paths with fewer function calls
- Consistent partition generation pattern across all lakehouse …
> Refactor lakehouse views to use generate_process_jit_partitions

- CLAUDE.md
- ai_tasks/jsonb_properties_disk_space_analysis_plan.md
- mkdocs/docs/assets/stylesheets/extra.css
- mkdocs/docs/query-guide/functions-reference.md
- rust/analytics/src/lakehouse/query.rs
- rust/analytics/src/properties/mod.rs
- rust/analytics/src/properties/properties_to_jsonb_udf.rs
- rust/analytics/tests/properties_to_jsonb_tests.rs
- Implement new `properties_to_jsonb` UDF for converting properties to efficient JSONB format
- Complete comprehensive analysis showing 28.5% memory reduction with dictionary JSONB
- Add comprehensive test coverage including dictionary-encoded arrays
- Document function with examples and performance benefits
- **UDF Implementation**: New `PropertiesToJsonb` scalar function converting List<Struct> or Dictionary to JSONB
- **Test Coverage**: 7 comprehensive test cases covering edge cases, nulls, and dictionary encoding
- **Performance Analysis**: Complete disk space analysis with real data from 1,131 process records
- **Documentation**: Added function reference with syntax, examples, and integration notes
- **Code Quality**: Fixed import ordering, added null checks, improved error handling …
> feat: implement properties_to_jsonb UDF for efficient storage

- ai_tasks/dictionary_encoding_for_properties.md
- Archives dictionary encoding research blocked by Parquet specification limitation
- Documents complete investigation including root cause analysis
- Preserves technical analysis for future reference
This PR archives the dictionary encoding analysis from the `properties_dict` branch that was blocked by a fundamental Parquet limitation. The investigation found that:
- Dictionary encoding of complex types (`Dictionary<Int32, List<Struct>>`) is not supported by the Parquet specification
- Cannot persist dictionary-encoded properties to Parquet files 
- Implementation works for in-memory processing but breaks storage pipeline
- Alternative approach needed (dict of jsonb) for properties schema changes
The complete implementation attempt is preserved in the archive tag: …
> docs: archive dictionary encoding analysis

- python/micromegas/tests/test_queries.py
- rust/Cargo.lock
- rust/Cargo.toml
- rust/analytics/src/lakehouse/get_payload_function.rs
- rust/analytics/src/lakehouse/perfetto_trace_execution_plan.rs
- rust/analytics/src/lakehouse/retire_partition_by_file_udf.rs
- rust/analytics/src/properties/properties_to_dict_udf.rs
- rust/analytics/src/properties/properties_to_jsonb_udf.rs
- rust/analytics/src/properties/property_get.rs
- rust/analytics/tests/properties_to_jsonb_tests.rs
- rust/analytics/tests/property_get_tests.rs
- rust/flight-sql-srv/src/flight_sql_srv.rs
- Update DataFusion from 49 to 50.0
- Update Arrow Flight from 55 to 56.1  
- Update Tonic from 0.12 to 0.13 for compatibility
- Add required trait implementations (PartialEq, Eq, Hash) to UDF structs
- Fix async method signatures for DataFusion 50.0 API changes
- Update Tonic interceptor usage for new API
- Fix test ScalarFunctionArgs to include config_options field
- Escape SQL reserved keywords in queries (END is now reserved in DataFusion)
> Update DataFusion and Arrow Flight dependencies
