- rust/telemetry/src/blob_storage.rs
allow blob storage without url parsing
> BlobStorage::new

- local_test_env/arm64/Dockerfile
- local_test_env/arm64/build.py
- local_test_env/arm64/run.py
- rust/tracing/src/dispatch.rs
- rust/tracing/src/time.rs
> fixed compilation for arm

- unreal/MicromegasTelemetrySink/Private/HttpEventSink.cpp
- unreal/MicromegasTelemetrySink/Private/MicromegasTelemetrySinkModule.cpp
- unreal/MicromegasTelemetrySink/Private/SamplingController.h
- unreal/MicromegasTelemetrySink/Public/MicromegasTelemetrySink/HttpEventSink.h
> [unreal] errors to warnings

- python/micromegas/micromegas/perfetto.py
- rust/analytics/src/call_tree.rs
- rust/analytics/src/thread_block_processor.rs
- rust/analytics/src/thread_events_table.rs
…y on spans rather than event to support fragmented traces
> perfetto fragmented trace support

- python/micromegas/micromegas/client.py
- python/micromegas/micromegas/perfetto.py
- rust/Cargo.toml
- rust/analytics-srv/src/main.rs
- rust/analytics/src/analytics_service.rs
- rust/telemetry-sink/Cargo.toml
- rust/telemetry-sink/src/local_event_sink.rs
+ [analytics] find_process api
+ [analytics] optional begin/end in query_streams
> Perfetto: simpler api to create a trace

- local_test_env/db/dump.py
- local_test_env/db/restore.py
- rust/analytics-srv/src/main.rs
- rust/ingestion/src/data_lake_connection.rs
- rust/ingestion/src/sql_migration.rs
- rust/ingestion/src/web_ingestion_service.rs
- rust/public/Cargo.toml
- rust/public/src/lib.rs
- rust/telemetry-admin-cli/Cargo.toml
- rust/telemetry-admin-cli/src/lake_size.rs
- rust/telemetry-admin-cli/src/main.rs
- rust/telemetry/Cargo.toml
- rust/telemetry/src/blob_storage.rs
+ dump & restore local postgresql database
> delete_old_blocks, schema v2

- python/micromegas/micromegas/client.py
- rust/analytics/src/analytics_service.rs
- rust/analytics/src/lakehouse/batch_update.rs
- rust/analytics/src/lakehouse/merge.rs
- rust/analytics/src/lakehouse/partition_source_data.rs
- rust/public/src/servers/analytics.rs
- rust/public/src/servers/maintenance.rs
- rust/telemetry-admin-cli/src/telemetry_admin.rs
merge existing partitions when possible, update from source data otherwise
> lakehouse auto partition update

- rust/Cargo.toml
- rust/analytics-srv/src/main.rs
Hello @madesroches 😄 
I've been playing with the idea of having a Gui for Micromegas over the weekend (https://github.com/gaku-sei/sirius) and needed this one change to make it work on the web. It's very basic (allow all origins, only POST methods) but it does the job. Let me know what you think 👍
> feat: Add cors middleware to analytics srv

- python/micromegas/cli/query_processes.py
- unreal/MicromegasTelemetrySink/Private/HttpEventSink.cpp
- use unreal projet name when there is no exe available
- [cli] sort processes by insert_time by default
> console support

- rust/Cargo.lock
- rust/analytics/src/log_entry.rs
- rust/analytics/src/payload.rs
- rust/analytics/tests/log_tests.rs
- rust/telemetry-sink/src/stream_info.rs
- rust/tracing/src/dispatch.rs
- rust/tracing/src/intern_string.rs
- rust/tracing/src/lib.rs
- rust/tracing/src/logs/block.rs
- rust/tracing/src/logs/events.rs
- rust/tracing/src/macros.rs
- rust/tracing/src/parsing.rs
- rust/tracing/src/property_set.rs
- rust/tracing/src/static_string_ref.rs
- rust/tracing/src/string_id.rs
- rust/tracing/tests/test_macros.rs
- rust/tracing/tests/utils.rs
- rust/transit/Cargo.toml
- rust/transit/derive/src/derive_reflect.rs
- rust/transit/src/parser.rs
- rust/transit/src/reflect.rs
- rust/transit/src/static_string.rs
- rust/transit/src/string_codec.rs
- rust/transit/src/value.rs
- rust/transit/tests/test_reflect.rs
+ ref count most copied strings 
+ move custom parsing of tracing structures in tracing crate
> Tagged log entries

- rust/analytics/src/measure.rs
- rust/analytics/tests/metrics_test.rs
- rust/ingestion/src/web_ingestion_service.rs
- rust/tracing/src/dispatch.rs
- rust/tracing/src/macros.rs
- rust/tracing/src/metrics/block.rs
- rust/tracing/src/metrics/events.rs
- rust/tracing/src/parsing.rs
- rust/tracing/tests/test_macros.rs
properties can override static attributes
> tagged measures now have both a static desc and a property set.

- rust/analytics/src/lakehouse/log_view.rs
- rust/analytics/src/lakehouse/metrics_view.rs
- rust/analytics/src/lakehouse/sql_batch_view.rs
- rust/analytics/src/log_entries_table.rs
- rust/analytics/src/log_entry.rs
- rust/analytics/src/measure.rs
- rust/analytics/src/metrics_table.rs
- rust/analytics/tests/log_tests.rs
- rust/analytics/tests/metrics_test.rs
- rust/analytics/tests/sql_view_test.rs
+ add insert_time to log view
+ add insert_time to measures view
> sql-defined view: use insert_time to limit source query

- rust/Cargo.lock
- rust/analytics/src/lakehouse/batch_update.rs
- rust/analytics/src/lakehouse/log_view.rs
- rust/analytics/src/lakehouse/metrics_view.rs
- rust/analytics/src/lakehouse/query.rs
- rust/analytics/src/lakehouse/sql_batch_view.rs
- rust/analytics/src/lakehouse/view.rs
- rust/analytics/tests/sql_view_test.rs
- rust/public/Cargo.toml
- rust/public/src/servers/cron_task.rs
- rust/public/src/servers/maintenance.rs
- rust/public/src/servers/mod.rs
+ schedule bigger tasks concurrently from the high frequency tasks in daemon
> limit partition size when creating from source

- rust/Cargo.lock
- rust/Cargo.toml
- rust/analytics/src/lakehouse/jit_partitions.rs
- rust/analytics/src/lakehouse/log_block_processor.rs
- rust/analytics/src/lakehouse/log_view.rs
- rust/analytics/src/lakehouse/metrics_block_processor.rs
- rust/analytics/src/lakehouse/metrics_view.rs
- rust/analytics/src/lakehouse/thread_spans_view.rs
- rust/analytics/src/metadata.rs
- rust/analytics/src/time.rs
- rust/analytics/tests/log_tests.rs
- rust/analytics/tests/metrics_test.rs
- rust/tracing/Cargo.toml
- rust/tracing/src/dispatch.rs
- rust/tracing/src/time.rs
on windows: use QueryPerformanceCounter/QueryPerformanceFrequency
else, on x86: _rdtsc
else on arm: use the virtual count register cntvct_el0
> tsc frequency robustness

- rust/public/src/servers/maintenance.rs
- execute `minute` task later
- in `second` task, don't process two time slices - only one
- bail with warning on seconds task if too late
> leaner schedule

- rust/analytics/tests/log_tests.rs
- rust/analytics/tests/metrics_test.rs
- rust/analytics/tests/span_tests.rs
- rust/analytics/tests/sql_view_test.rs
- rust/telemetry-sink/src/lib.rs
- rust/tracing/src/dispatch.rs
- rust/tracing/src/guards.rs
- rust/tracing/src/lib.rs
- rust/tracing/tests/test_macros.rs
This PR exposes the process properties hashmap to the Telemetry system guard.
> Exposed process properties in telemetry guards

- rust/analytics/src/lakehouse/get_payload_function.rs
- rust/analytics/src/lakehouse/mod.rs
- rust/analytics/src/lakehouse/property_get_function.rs
- rust/analytics/src/lakehouse/query.rs
will be useful for replication
> GetPayload user defined function

- README.md
Updated the second objective in README.md to clarify that quantifying issue frequency and severity allows for better priority management.
> docs: Update README objectives

- README.md
- ai_tasks/future_tasks.md
• Updated August 2025 section with recent async span tracing work
• Replaced generic infrastructure descriptions with specific feature highlights
• Added named async span events, depth tracking, async trait support, and performance optimizations
> Update README with August 2025 development highlights

- CLAUDE.md
- ai_tasks/perfetto_async_spans_plan.md
- mkdocs/docs/query-guide/schema-reference.md
- python/micromegas/tests/test_processes.py
- python/notebooks/async_traces.ipynb
- python/notebooks/lakehouse_partitions.ipynb
- rust/Cargo.lock
- rust/analytics/src/lakehouse/async_events_block_processor.rs
- rust/analytics/src/lakehouse/async_events_view.rs
- rust/analytics/src/lakehouse/processes_view.rs
- rust/analytics/src/lakehouse/view_factory.rs
- rust/analytics/src/metadata.rs
- rust/analytics/src/time.rs
- rust/analytics/tests/async_events_tests.rs
- rust/analytics/tests/time_tests.rs
- rust/perfetto/examples/streaming_comparison.rs
- rust/perfetto/src/lib.rs
- rust/perfetto/src/streaming_writer.rs
- rust/perfetto/src/writer.rs
- rust/perfetto/tests/streaming_writer_tests.rs
- rust/public/src/servers/flight_sql_service_impl.rs
- rust/trace-gen-util/Cargo.toml
- rust/trace-gen-util/README.md
- rust/trace-gen-util/src/main.rs
- rust/trace-gen-util/src/validate_trace.rs
- rust/tracing/proc-macros/src/lib.rs
- rust/tracing/src/test_utils.rs
- rust/transit/src/uuid_utils.rs
- Complete implementation of Perfetto async spans visualization support
- Add streaming writer infrastructure for memory-efficient trace generation  
- Fix timestamp reliability and stream filtering issues in trace generation
- Add comprehensive test coverage and end-to-end validation
> Implement Perfetto async spans support with trace generation

- ai_tasks/document_python_api.md
- mkdocs/docs/query-guide/python-api-advanced.md
- mkdocs/docs/query-guide/python-api.md
- mkdocs/mkdocs.yml
- python/micromegas/README.md
- python/micromegas/micromegas/flightsql/client.py
- python/micromegas/micromegas/time.py
- Added comprehensive docstrings to all public Python API methods (100% coverage)
- Updated Python API documentation page with all missing methods and examples
- Created advanced Python API guide with performance optimization patterns
- Added specialized data management workflows and error handling examples
This completes the Python API documentation initiative, providing both reference documentation and advanced usage patterns for Micromegas users.
> Complete Python API documentation with comprehensive docstrings and advanced guide

- mkdocs/docs/query-guide/schema-reference.md
Add documentation for the log_stats materialized view which provides aggregated log statistics by process, minute, level, and target. Includes field descriptions and example queries for log volume analysis.
> docs: add log_stats view to schema reference
